image: joeoi/mson-to-json-schema

stages:
    - build-json-schema
    - commit-json-schema

build-json-schema:
    tags:
        - docker
    stage: build-json-schema
    script: bash -l "mson-to-json-schema.sh"
    artifacts:
        unchecked: true
        paths:
            - entries/

commit-json-schema:
    tags:
        - docker
    stage: commit-json-schema
    script: bash -l "commit-json-schema.sh"
    dependencies:
        - build-json-schema

variables:
    GH_USERNAME: jmatsushita
    GH_EMAIL: jun@iilab.org
    CONFIG_OWNER: openintegrity
    CONFIG_REPO: openintegrity.org
